version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  api_service:
    depends_on:
      - mysqldb
    image: devops-project-1
    container_name: devops-project-1-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    restart: always
    environment:
      SPRING_DATASOURCE_URL:  jdbc:mysql://mysqldb:3306/sampledb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db: